[pytest]
filterwarnings =
    error:.*on_event is deprecated.*:DeprecationWarning
    error:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning
    error:The `name` is not the first parameter anymore.*:DeprecationWarning
    error:Identity map already had an identity.*:sqlalchemy.exc.SAWarning
