"""initial schema

Revision ID: 4dc3c5aaf598
Revises: 
Create Date: 2026-08-14 11:09:25.620881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc3c5aaf598'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('username_normalized', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_username_normalized'), 'users', ['username_normalized'], unique=True)
    op.create_table('configuration_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_number', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimates_estimate_number'), 'estimates', ['estimate_number'], unique=True)
    op.create_table('config_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_version_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_key', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['configuration_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_version_id', 'category', 'key', name='uq_config_item_version_category_key')
    )
    op.create_index(op.f('ix_config_items_category'), 'config_items', ['category'], unique=False)
    op.create_index(op.f('ix_config_items_config_version_id'), 'config_items', ['config_version_id'], unique=False)
    op.create_index(op.f('ix_config_items_key'), 'config_items', ['key'], unique=False)
    op.create_index(op.f('ix_config_items_parent_key'), 'config_items', ['parent_key'], unique=False)
    op.create_table('estimate_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config_version_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('customer_type', sa.String(length=40), nullable=False),
    sa.Column('opportunity_number', sa.String(length=120), nullable=False),
    sa.Column('proposal_date', sa.Date(), nullable=True),
    sa.Column('project_start', sa.Date(), nullable=True),
    sa.Column('billing_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=240), nullable=False),
    sa.Column('upgrade_type', sa.String(length=120), nullable=False),
    sa.Column('upgrade_app_count', sa.Integer(), nullable=False),
    sa.Column('android_change', sa.Boolean(), nullable=False),
    sa.Column('project_type', sa.String(length=80), nullable=False),
    sa.Column('erp', sa.String(length=100), nullable=False),
    sa.Column('high_availability', sa.Boolean(), nullable=False),
    sa.Column('gateway', sa.Boolean(), nullable=False),
    sa.Column('epp_install', sa.String(length=30), nullable=False),
    sa.Column('epp_integration', sa.String(length=50), nullable=False),
    sa.Column('label_sites', sa.Integer(), nullable=False),
    sa.Column('labels_required', sa.Boolean(), nullable=False),
    sa.Column('label_count', sa.Integer(), nullable=False),
    sa.Column('iot_required', sa.Boolean(), nullable=False),
    sa.Column('iot_count', sa.Integer(), nullable=False),
    sa.Column('erp_integration_required', sa.Boolean(), nullable=False),
    sa.Column('erp_integration_count', sa.Integer(), nullable=False),
    sa.Column('data_rep_required', sa.Boolean(), nullable=False),
    sa.Column('data_rep_count', sa.Integer(), nullable=False),
    sa.Column('consultant_access_setup', sa.Boolean(), nullable=False),
    sa.Column('onboarding', sa.Boolean(), nullable=False),
    sa.Column('user_count', sa.String(length=40), nullable=False),
    sa.Column('test_cycles', sa.Integer(), nullable=False),
    sa.Column('go_live_sites', sa.Integer(), nullable=False),
    sa.Column('go_live_type', sa.String(length=60), nullable=False),
    sa.Column('uat_sites', sa.Integer(), nullable=False),
    sa.Column('base_test_pct', sa.Float(), nullable=False),
    sa.Column('pacejet', sa.Boolean(), nullable=False),
    sa.Column('write_test_scripts', sa.Boolean(), nullable=False),
    sa.Column('security_method', sa.String(length=30), nullable=False),
    sa.Column('end_user_documentation', sa.Boolean(), nullable=False),
    sa.Column('end_user_training', sa.Boolean(), nullable=False),
    sa.Column('app_dev_training', sa.Boolean(), nullable=False),
    sa.Column('delivery_method', sa.String(length=40), nullable=False),
    sa.Column('unit_test_factor_override', sa.Float(), nullable=True),
    sa.Column('unit_test_override_reason', sa.Text(), nullable=True),
    sa.Column('calculated_hours', sa.Float(), nullable=False),
    sa.Column('calculated_fees', sa.Float(), nullable=False),
    sa.Column('low_hours', sa.Float(), nullable=False),
    sa.Column('high_hours', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Float(), nullable=False),
    sa.Column('schedule_needs_refresh', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['configuration_versions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_id', 'revision_no', name='uq_estimate_revision')
    )
    op.create_index(op.f('ix_estimate_revisions_estimate_id'), 'estimate_revisions', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_estimate_revisions_status'), 'estimate_revisions', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('config_version_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('field_name', sa.String(length=160), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['configuration_versions.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_config_version_id'), 'audit_events', ['config_version_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_estimate_id'), 'audit_events', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_revision_id'), 'audit_events', ['revision_id'], unique=False)
    op.create_table('calculation_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=120), nullable=False),
    sa.Column('adjust_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'line_key', name='uq_calc_adjustment')
    )
    op.create_index(op.f('ix_calculation_adjustments_revision_id'), 'calculation_adjustments', ['revision_id'], unique=False)
    op.create_table('detail_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('mod_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'line_key', name='uq_detail_adjustment')
    )
    op.create_index(op.f('ix_detail_adjustments_revision_id'), 'detail_adjustments', ['revision_id'], unique=False)
    op.create_table('estimate_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('catalog_key', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('config_type', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimate_applications_revision_id'), 'estimate_applications', ['revision_id'], unique=False)
    op.create_table('estimate_custom_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('complexity', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimate_custom_applications_revision_id'), 'estimate_custom_applications', ['revision_id'], unique=False)
    op.create_table('schedule_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('task', sa.String(length=240), nullable=False),
    sa.Column('task_owner', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('resource_assigned', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('percent_complete', sa.Integer(), nullable=False),
    sa.Column('non_bill_hours', sa.Float(), nullable=False),
    sa.Column('billable_hours_budgeted', sa.Float(), nullable=False),
    sa.Column('change_order_hours', sa.Float(), nullable=False),
    sa.Column('hours_used', sa.Float(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_tasks_revision_id'), 'schedule_tasks', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_tasks_revision_id'), table_name='schedule_tasks')
    op.drop_table('schedule_tasks')
    op.drop_index(op.f('ix_estimate_custom_applications_revision_id'), table_name='estimate_custom_applications')
    op.drop_table('estimate_custom_applications')
    op.drop_index(op.f('ix_estimate_applications_revision_id'), table_name='estimate_applications')
    op.drop_table('estimate_applications')
    op.drop_index(op.f('ix_detail_adjustments_revision_id'), table_name='detail_adjustments')
    op.drop_table('detail_adjustments')
    op.drop_index(op.f('ix_calculation_adjustments_revision_id'), table_name='calculation_adjustments')
    op.drop_table('calculation_adjustments')
    op.drop_index(op.f('ix_audit_events_revision_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_estimate_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_config_version_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_estimate_revisions_status'), table_name='estimate_revisions')
    op.drop_index(op.f('ix_estimate_revisions_estimate_id'), table_name='estimate_revisions')
    op.drop_table('estimate_revisions')
    op.drop_index(op.f('ix_config_items_parent_key'), table_name='config_items')
    op.drop_index(op.f('ix_config_items_key'), table_name='config_items')
    op.drop_index(op.f('ix_config_items_config_version_id'), table_name='config_items')
    op.drop_index(op.f('ix_config_items_category'), table_name='config_items')
    op.drop_table('config_items')
    op.drop_index(op.f('ix_estimates_estimate_number'), table_name='estimates')
    op.drop_table('estimates')
    op.drop_table('configuration_versions')
    op.drop_index(op.f('ix_users_username_normalized'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
